### ISSUE TITLE
Compatibility with RVV 0.10

### ISSUE THREAD

**Issue by suehtamacv** [pulp-platform/ara#1]
Once the RISC-V GCC toolchain and the Spike simulator have been updated to version 0.10, the same can be done with Ara. 

In terms of microarchitectural changes, RVV 0.10 deprecates the `SLEN` parameter, the striping distance being set as being always equal to the vector length `VLEN`. Current Ara already takes this into account, since it considers that `SLEN = VLEN`.

Other RVV-upgrade changes include the implementation of extra floating-point instructions, and encoding changes with a few vector CSRs.

**Comment by mp-17** [comment]
I tried the `rvv-intrinsic` branch of the toolchain, and it produces instructions in compliance with RVV 0.10 (run with SPIKE RVV 0.10).
