### ISSUE TITLE
Ask for help about the configuration option in make

### ISSUE THREAD

**Issue by huanpass** [pulp-platform/ara#103]
Can i ask how to use this in the RTL simulation? 
Prepend config=chosen_ara_configuration to your Makefile commands

Is it              config=8_lanes   make verilate  ？
Or               config=8_lanes   make riscv_tests_simv

Many thanks!

**Comment by mp-17** [comment]
Hello @huanpass,

You need `config=8_lanes make verilate`. This compiles the system with 8 lanes and creates the verilated model.
Then, you need the `config=8_lanes make riscv_tests`, or `config=8_lanes make bin/${program}` in the `apps` folder, when you are compiling the riscv-tests or programs.

Using `config=8_lanes make riscv_tests_simv` is not strictly necessary in this particular case, but I would suggest you to always append it to the make command for clarity, and not to make confusion.

Best regards,
Matteo
