### ISSUE TITLE
Masked instructions lead to freeze

### ISSUE THREAD

**Issue by Vikitator** [pulp-platform/ara#105]
When running a simple kernel that computes the absolute of a vector using mask instructions, Ara freezes since commit 7ac8ce4. Release v2.2.0 works as expected.

    vle64.v v8, (a0)
    vmslt.vx v0, v8, zero
    vneg.v v8, v8, v0.t
    vse64.v v8, (a0)

**Comment by mp-17** [comment]
Hello @Vikitator, 
Thanks a lot for reporting this! I will add the fix in the next PR!

**Comment by mp-17** [comment]
Addressed with https://github.com/pulp-platform/ara/pull/101
