### ISSUE TITLE
How ara implements the chaining between vector instructions?

### ISSUE THREAD

**Issue by Zissi-Lei** [pulp-platform/ara#109]
I notice that there is no forwarding logic between the result queue and operand queue. So I want to known howara implements the chaining between vector instructions?  I think the chaining is done by reading the result form VRF that the result queue just write to. Is that true? Thanks for you time!

**Comment by mp-17** [comment]
Hello @Zissi-Lei,

Exactly. Data can chain only by passing through the VRF first. The result queues write to the VRF, and then the single elements can be then fetched as operands.

Best,
Matteo
