### ISSUE TITLE
Compute bound regime of ara.

### ISSUE THREAD

**Issue by Zissi-Lei** [pulp-platform/ara#121]
In your paper "Ara: A 1 GHz+ Scalable and Energy-Efficient RISC-V Vector Processor with Multi-Precision Floating Point Support in 22 nm FD-SOI", you said that "For Ara, it enters its computebound regime when the arithmetic intensity is higher than 0.5 DP−FLOP/B". How do you calculate this value? Thanks.

**Comment by mp-17** [comment]
Hello @Zissi-Lei,

Ara can execute 1 MACC/cycle in each lane. If you count MACC operations as 2 DP-FLOP, the max throughput of Ara is: 

`2 * NrLanes [DP-FLOP/cycle]`

The memory bus is parametrized to be `32 * NrLanes` bits wide (this is a design choice that leads the max memory throughput to be half of the max computational one). 
This is the maximum amount of data transferred per cycle on the memory interface. In Bytes: 

`4 * NrLanes [B/cycle]`

If you calculate the ratio, you get `0.5 DP−FLOP/B`.

Best,
Matteo
