### ISSUE TITLE
Error in building spike!

### ISSUE THREAD

**Issue by StyleDiablo** [pulp-platform/ara#153]
Hello, I cloned the repository I built the LLVM toolchain no problembt when I attempt to build to bild Spike i Get this error:

**../riscv/interactive.cc: In member function ‘void sim_t::interactive_fregd_all(const string&, const std::vector<std::__cxx11::basic_string<char> >&)’:
../riscv/interactive.cc:639:21: error: ‘class processor_t’ has no member named ‘get_max_xlen’; did you mean ‘get_xlen’?
  639 |   int max_xlen = p->get_max_xlen();
      |                     ^~~~~~~~~~~~
      |                     get_xlen**

How can I fix this?
Thank you.

**Comment by mp-17** [comment]
Hello @StyleDiablo,

The released patch had one missing line! Thanks for noticing. 
This PR should solve the problem: https://github.com/pulp-platform/ara/pull/154

Let us know,
Matteo
