### ISSUE TITLE
What VLEN do you use in area evaluation?

### ISSUE THREAD

**Issue by Zissi-Lei** [pulp-platform/ara#177]
In your paper "https://arxiv.org/pdf/1906.00478.pdf", you showed area results in different LANES.
But I can't find what VLEN is in each result.
Can you give it detailly about what VLEN you use in each LANES? Thanks.

**Comment by suehtamacv** [comment]
Hello @Zissi-Lei! That paper was written before `VLEN` was defined as a parameter. You can refer to our updated work, https://ieeexplore.ieee.org/abstract/document/9912071, for more information about the `VLEN` used for our area estimations. Let me know if you have further questions!
