### ISSUE TITLE
How to calculate computing power in Ara?

### ISSUE THREAD

**Issue by Zissi-Lei** [pulp-platform/ara#215]
Hi,
In "V. Performance Analysis->B. AXPY" of your paper "Ara: A 1-GHz+ Scalable and Energy-Efficient RISC-V Vector Processor With Multiprecision Floating-Point Support in 22-nm FD-SOI", you said that "For an Ara instance with two lanes, we measure 0.65 DP−FLOP/cycle, ...". I want to know how to get that result? It's that operations/(Consumed cycles in AXPY program)? Thanks for your time.

**Comment by mp-17** [comment]
Hello @Zissi-Lei,

From the paper:

```
DAXPY, Y ← αX +Y, is a common algorithmic building block
of more complex Basic Linear Algebra Subprograms (BLAS)
routines. Considering vectors of length n, DAXPY requires n
FMAs and at least 24n bytes of memory transfers. DAXPY is
therefore a heavily memory-bound algorithm, with an arithmetic
intensity of 1/12 DP−FLOP/B.
```

The kernel requires `n` FMAs, i.e., `2*n` operations (1 FMA == 2 OPs).
So, to find the raw performance (OPs/cycle), you can divide the total number of useful operations by the number of clock cycles.
