### ISSUE TITLE
[Question] Neutral value of FP-reductions

### ISSUE THREAD

**Issue by jin8495** [pulp-platform/ara#231]
Hi, while I am reading your code, I have a question about the VMFPU.

In VALU, neutral values come from the operand queue so that the VALU does not have to generate the neutral value, and keeps taking operands from the op_queues and pushing them into the simd_alu.
However, VMFPU takes a different approach even though the op_queues can generate neutral values for the floating-points. It generates neutral value by itself.

Do they have to be different? or just a historical issue of development?

**Comment by mp-17** [comment]
Hello @jin8495,

Thanks for the question, and sorry for the late answer. 
It's just historical reasons :-)
At the first codebase refactoring, this will be aligned.

Best,
Matteo
