### ISSUE TITLE
Does ara adopt out-of-order commit?

### ISSUE THREAD

**Issue by TimLee-123** [pulp-platform/ara#263]
### **Issue**
When performing formal verification on ARA, I observed occurrences of out-of-order commit, contrary to what appears to be stated in ARA's paper as an in-order execution.

The waveform I'm currently reviewing shows that the vslideup instruction (vid = 3) is issued after the vadd instruction (vid = 2). However, the vslideup instruction writes back to VRF earlier than the vadd instruction.

If there's anything I'm considering wrong, please let me know, thanks!

### **Supplementary Pictures**
![image](https://github.com/pulp-platform/ara/assets/145886969/90526bb1-37b8-41b8-8df7-6345b0287e85)

![圖片21](https://github.com/pulp-platform/ara/assets/145886969/43c61d59-4f48-41c8-aaf9-32952ccb55ba)

![image](https://github.com/pulp-platform/ara/assets/145886969/a3ebfbae-7401-445c-9bf8-cc5d05ccd928)

![image](https://github.com/pulp-platform/ara/assets/145886969/808650d7-f19b-429f-864f-9b845da0a8d9)

**Comment by mp-17** [comment]
Hello @TimLee-123, 

Ara can commit out-of-order, but the instruction issue is strictly non-speculative and in-order.

Best,
Matteo
