### ISSUE TITLE
Compatibility with RVV intrinsics

### ISSUE THREAD

**Issue by mp-17** [pulp-platform/ara#28]
The RISC-V community is working on instrinsics to ease the C-level programmability: https://github.com/riscv/rvv-intrinsic-doc.
The related branch of the `riscv-toolchain` (`rvv-intrinsic`, https://github.com/riscv/riscv-gnu-toolchain/tree/rvv-intrinsic) produces code compliant with the version 0.10 of the specs.
To support the intrinsics, we need to:

- Update SPIKE
- Update the toolchain
- Update Ara (https://github.com/pulp-platform/ara/issues/1)

**Comment by suehtamacv** [comment]
What is the status of this issue? Since #40 was merged, can we close it?

**Comment by mp-17** [comment]
Yes, definetly!
