### ISSUE TITLE
VRF address error

### ISSUE THREAD

**Issue by TimLee-123** [pulp-platform/ara#286]
### **Issue**
When the VLEN parameter of the vaddr function is too small or the number of Nrlanes is too high, the address will remain at 0. This can lead to a situation where different vector registers share storage space.

### **Supplementary Pictures**

![image](https://github.com/pulp-platform/ara/assets/145886969/c3876145-b655-4fc8-b5e2-dec0369f2166)

![image](https://github.com/pulp-platform/ara/assets/145886969/684e3495-9231-4973-b193-09c4d1d3c95a)

**Comment by mp-17** [comment]
Hey @TimLee-123, 
This happens since we need at least 8 Byte per lane. Handling this [here](https://github.com/pulp-platform/ara/pull/353/commits/765714c405beff5f15c4d7807a3b787bd9a69d1f) in https://github.com/pulp-platform/ara/pull/353.
