### ISSUE TITLE
Multi Core Setup Simulation

### ISSUE THREAD

**Issue by AdhamRagab25** [pulp-platform/ara#291]
Hello @mp-17;

Thanks for your quick responses to #289! I am also interested in testing some of the multi-core setup in your project, and was curious about your preferred methods for simulation. For context, I was previously experimenting on the main branch prior to discovering the paper, and subsequently the branch and this issue. I have been using Verilator almost exclusively due to some Questa/ModelSim setup issues on my end. I'm curious if you used Verilator at all to simulate some multi-core setups, or if you tended to favour Questa/ModelSim. For the later, considering it can quite exciting to observe how it works, I might consider taking some time to fix my Questa/ModelSim issues. However, if you did use Verilator, I am curious in how you got it to simulate, as I am running into issues trying to use it.

Thanks in advance!

**Comment by mp-17** [comment]
Hey @AdhamRagab25,

For the multi-core setup, we only used QuestaSim. Unluckily, we did not fix the RTL to be compiled with Verilator, so I am not surprised it does not work smoothly with it :-/

**Comment by AdhamRagab25** [comment]
Thanks so much for your reply! I'll sort out my issues with QuestaSim then and get simulating - this is exciting, thank you!

**Comment by shkim-emily** [comment]
Hello! I clone the feat/multi-core branch for running multi-core simulation.. 
How can I install QuestaSim? 
Could you share how to run the simulation?
