### ISSUE TITLE
How to accelerate the verilator compile time?

### ISSUE THREAD

**Issue by sodargreen** [pulp-platform/ara#297]
When I set the lane=16, it costs about more than 10 mins to finish the verilator compiling. 
I've tried the argument "-j" "--thread" but it doesn't work. Can you help me?

**Comment by mp-17** [comment]
Hello @sodargreen,

You can try to compile more modules hierarchically (https://verilator.org/guide/latest/verilating.html#hierarchical-verilation). Thus far, we are only compiling the lane hierarchically. If you want to add directives for hierarchical compilation, you can do it here: https://github.com/pulp-platform/ara/blob/main/hardware/tb/verilator/waiver.vlt
