### ISSUE TITLE
Change the binding between vector register operands and operand queues

### ISSUE THREAD

**Issue by mp-17** [pulp-platform/ara#3]
Following the official specifications, RISC-V vector arithmetical instructions use `vs2` as the first/only operand and `vs1` as the second operand. However, the current mapping from vector registers to operand queues is:

- `vs1` to `OpQueueA`
- `vs2` to `OpQueueB`
- `vd` to `OpQueueC`

This mapping is not intuitive, as the first/only operand goes to `OpQueueB`. I propose to change the mapping to:

- `vs1` to `OpQueueB`
- `vs2` to `OpQueueA`
- `vd` to `OpQueueC`

**Comment by suehtamacv** [comment]
What would be the benefit of doing this? Which files would be impacted?
