### ISSUE TITLE
Ensure correct execution when vl = 0

### ISSUE THREAD

**Issue by mp-17** [pulp-platform/ara#30]
When `vl = 0`, vector loads do not work as expected and generate undefined behaviour.

**Comment by suehtamacv** [comment]
I believe any instruction with `vl = 0` can be considered as a NOP. The main dispatcher can drop them.

**Comment by mp-17** [comment]
I thought the same thing, but maybe some instructions must still be able to raise exceptions (e.g., exceptions related to the address). What do you think about that?

**Comment by suehtamacv** [comment]
Which address?

**Comment by mp-17** [comment]
For example, an address generated for a load. But I agree that we can avoid generating the exception since no elements should be loaded.

**Comment by mp-17** [comment]
Addressed with this commit (https://github.com/pulp-platform/ara/commit/9f2eda8317de2e443ed1b0cd885bebc686cb46ce): I'll create a MR after the current `hotfixes` will be implemented.
