### ISSUE TITLE
RISC-V tests failing

### ISSUE THREAD

**Issue by Vinay0203** [pulp-platform/ara#305]
Hi, I am trying to clone the ara repository , built the toolchain in my Ubuntu system. 
After cloning the repository, while building the toolchain, i am getting the following failures:
`-- Could NOT find Terminfo (missing: Terminfo_LIBRARIES Terminfo_LINKABLE) 
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
-- Could NOT find LibXml2 (missing: LIBXML2_LIBRARY) (found version "2.9.13")
CMake Warning at cmake/Modules/CompilerRTUtils.cmake:326 (message):
  LLVMTestingSupport not found in LLVM_AVAILABLE_LIBS
Call Stack (most recent call first):
  CMakeLists.txt:83 (load_llvm_config)

-- LLVM_MAIN_SRC_DIR: "/home/pescampus/Desktop/ARA/ara/toolchain/riscv-llvm/llvm"
-- Found Python3: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter 
-- Performing Test CXX_SUPPORTS_UNWINDLIB_NONE_FLAG
-- Performing Test CXX_SUPPORTS_UNWINDLIB_NONE_FLAG - Failed
-- Looking for fopen in c
-- Looking for fopen in c - not found
-- Looking for __gcc_personality_v0 in gcc_s
-- Looking for __gcc_personality_v0 in gcc_s - not found
-- Performing Test C_SUPPORTS_NODEFAULTLIBS_FLAG
-- Performing Test C_SUPPORTS_NODEFAULTLIBS_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FFREESTANDING_FLAG
-- Performing Test COMPILER_RT_HAS_FFREESTANDING_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_OMIT_FRAME_POINTER_FLAG
-- Performing Test COMPILER_RT_HAS_OMIT_FRAME_POINTER_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_STD_C11_FLAG
-- Performing Test COMPILER_RT_HAS_STD_C11_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FCF_PROTECTION_FLAG
-- Performing Test COMPILER_RT_HAS_FCF_PROTECTION_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FPIC_FLAG
-- Performing Test COMPILER_RT_HAS_FPIC_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FPIE_FLAG
-- Performing Test COMPILER_RT_HAS_FPIE_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FNO_BUILTIN_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_BUILTIN_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FNO_EXCEPTIONS_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_EXCEPTIONS_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FOMIT_FRAME_POINTER_FLAG
-- Performing Test COMPILER_RT_HAS_FOMIT_FRAME_POINTER_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FUNWIND_TABLES_FLAG
-- Performing Test COMPILER_RT_HAS_FUNWIND_TABLES_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FNO_STACK_PROTECTOR_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_STACK_PROTECTOR_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FNO_SANITIZE_SAFE_STACK_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_SANITIZE_SAFE_STACK_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FVISIBILITY_HIDDEN_FLAG
-- Performing Test COMPILER_RT_HAS_FVISIBILITY_HIDDEN_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FRTTI_FLAG
-- Performing Test COMPILER_RT_HAS_FRTTI_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FNO_RTTI_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_RTTI_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FNO_FUNCTION_SECTIONS_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_FUNCTION_SECTIONS_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FTLS_MODEL_INITIAL_EXEC
-- Performing Test COMPILER_RT_HAS_FTLS_MODEL_INITIAL_EXEC - Failed
-- Performing Test COMPILER_RT_HAS_FNO_LTO_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_LTO_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FNO_PROFILE_GENERATE_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_PROFILE_GENERATE_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FNO_PROFILE_INSTR_GENERATE_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_PROFILE_INSTR_GENERATE_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FNO_PROFILE_INSTR_USE_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_PROFILE_INSTR_USE_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FNO_COVERAGE_MAPPING_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_COVERAGE_MAPPING_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_MCRC32_FLAG
-- Performing Test COMPILER_RT_HAS_MCRC32_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_MSSE3_FLAG
-- Performing Test COMPILER_RT_HAS_MSSE3_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_MSSE4_2_FLAG
-- Performing Test COMPILER_RT_HAS_MSSE4_2_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_SYSROOT_FLAG
-- Performing Test COMPILER_RT_HAS_SYSROOT_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_MCRC_FLAG
-- Performing Test COMPILER_RT_HAS_MCRC_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FNO_PARTIAL_INLINING_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_PARTIAL_INLINING_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_FVISIBILITY_INLINES_HIDDEN_FLAG
-- Performing Test COMPILER_RT_HAS_FVISIBILITY_INLINES_HIDDEN_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_GR_FLAG
-- Performing Test COMPILER_RT_HAS_GR_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_GS_FLAG
-- Performing Test COMPILER_RT_HAS_GS_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_MT_FLAG
-- Performing Test COMPILER_RT_HAS_MT_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_Oy_FLAG
-- Performing Test COMPILER_RT_HAS_Oy_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_GLINE_TABLES_ONLY_FLAG
-- Performing Test COMPILER_RT_HAS_GLINE_TABLES_ONLY_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_G_FLAG
-- Performing Test COMPILER_RT_HAS_G_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_Zi_FLAG
-- Performing Test COMPILER_RT_HAS_Zi_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WALL_FLAG
-- Performing Test COMPILER_RT_HAS_WALL_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WERROR_FLAG
-- Performing Test COMPILER_RT_HAS_WERROR_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WFRAME_LARGER_THAN_FLAG
-- Performing Test COMPILER_RT_HAS_WFRAME_LARGER_THAN_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WGLOBAL_CONSTRUCTORS_FLAG
-- Performing Test COMPILER_RT_HAS_WGLOBAL_CONSTRUCTORS_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WC99_EXTENSIONS_FLAG
-- Performing Test COMPILER_RT_HAS_WC99_EXTENSIONS_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WGNU_FLAG
-- Performing Test COMPILER_RT_HAS_WGNU_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WNON_VIRTUAL_DTOR_FLAG
-- Performing Test COMPILER_RT_HAS_WNON_VIRTUAL_DTOR_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WVARIADIC_MACROS_FLAG
-- Performing Test COMPILER_RT_HAS_WVARIADIC_MACROS_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WUNUSED_PARAMETER_FLAG
-- Performing Test COMPILER_RT_HAS_WUNUSED_PARAMETER_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WCOVERED_SWITCH_DEFAULT_FLAG
-- Performing Test COMPILER_RT_HAS_WCOVERED_SWITCH_DEFAULT_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WSUGGEST_OVERRIDE_FLAG
-- Performing Test COMPILER_RT_HAS_WSUGGEST_OVERRIDE_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WNO_PEDANTIC
-- Performing Test COMPILER_RT_HAS_WNO_PEDANTIC - Failed
-- Performing Test COMPILER_RT_HAS_WNO_FORMAT
-- Performing Test COMPILER_RT_HAS_WNO_FORMAT - Failed
-- Performing Test COMPILER_RT_HAS_WNO_FORMAT_PEDANTIC
-- Performing Test COMPILER_RT_HAS_WNO_FORMAT_PEDANTIC - Failed
-- Performing Test COMPILER_RT_HAS_EXTERNAL_FLAG
-- Performing Test COMPILER_RT_HAS_EXTERNAL_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_W4_FLAG
-- Performing Test COMPILER_RT_HAS_W4_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WX_FLAG
-- Performing Test COMPILER_RT_HAS_WX_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WD4146_FLAG
-- Performing Test COMPILER_RT_HAS_WD4146_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WD4206_FLAG
-- Performing Test COMPILER_RT_HAS_WD4206_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WD4291_FLAG
-- Performing Test COMPILER_RT_HAS_WD4291_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WD4221_FLAG
-- Performing Test COMPILER_RT_HAS_WD4221_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WD4391_FLAG
-- Performing Test COMPILER_RT_HAS_WD4391_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WD4722_FLAG
-- Performing Test COMPILER_RT_HAS_WD4722_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_WD4800_FLAG
-- Performing Test COMPILER_RT_HAS_WD4800_FLAG - Failed
-- Performing Test -Warray-bounds
-- Performing Test -Warray-bounds - Failed
-- Performing Test -Wuninitialized
-- Performing Test -Wuninitialized - Failed
-- Performing Test -Wshadow
-- Performing Test -Wshadow - Failed
-- Performing Test -Wempty-body
-- Performing Test -Wempty-body - Failed
-- Performing Test -Wsizeof-pointer-memaccess
-- Performing Test -Wsizeof-pointer-memaccess - Failed
-- Performing Test -Wsizeof-array-argument
-- Performing Test -Wsizeof-array-argument - Failed
-- Performing Test -Wsuspicious-memaccess
-- Performing Test -Wsuspicious-memaccess - Failed
-- Performing Test -Wbuiltin-memcpy-chk-size
-- Performing Test -Wbuiltin-memcpy-chk-size - Failed
-- Performing Test -Warray-bounds-pointer-arithmetic
-- Performing Test -Warray-bounds-pointer-arithmetic - Failed
-- Performing Test -Wreturn-stack-address
-- Performing Test -Wreturn-stack-address - Failed
-- Performing Test -Wsizeof-array-decay
-- Performing Test -Wsizeof-array-decay - Failed
-- Performing Test -Wformat-insufficient-args
-- Performing Test -Wformat-insufficient-args - Failed
-- Performing Test -Wformat-security
-- Performing Test -Wformat-security - Failed
-- Performing Test -Wsizeof-array-div
-- Performing Test -Wsizeof-array-div - Failed
-- Performing Test -Wsizeof-pointer-div
-- Performing Test -Wsizeof-pointer-div - Failed
-- Looking for __func__
-- Looking for __func__ - not found
-- Performing Test COMPILER_RT_HAS_NOSTDINCXX_FLAG
-- Performing Test COMPILER_RT_HAS_NOSTDINCXX_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_NOSTDLIBXX_FLAG
-- Performing Test COMPILER_RT_HAS_NOSTDLIBXX_FLAG - Failed
-- Looking for include file sys/auxv.h
-- Looking for include file sys/auxv.h - not found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - not found
-- Looking for shm_open in rt
-- Looking for shm_open in rt - not found
-- Looking for pow in m
-- Looking for pow in m - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Looking for backtrace in execinfo
-- Looking for backtrace in execinfo - not found
-- Looking for __cxa_throw in c++
-- Looking for __cxa_throw in c++ - not found
-- Looking for __cxa_throw in stdc++
-- Looking for __cxa_throw in stdc++ - not found
-- Performing Test COMPILER_RT_HAS_Z_TEXT
-- Performing Test COMPILER_RT_HAS_Z_TEXT - Failed
-- Performing Test COMPILER_RT_HAS_FUSE_LD_LLD_FLAG
-- Performing Test COMPILER_RT_HAS_FUSE_LD_LLD_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_VERSION_SCRIPT
-- Performing Test COMPILER_RT_HAS_VERSION_SCRIPT - Failed
-- Compiler-RT supported architectures: riscv64
-- Performing Test COMPILER_RT_HAS_VISIBILITY_HIDDEN_FLAG
-- Performing Test COMPILER_RT_HAS_VISIBILITY_HIDDEN_FLAG - Success
-- Performing Test COMPILER_RT_HAS_XRAY_COMPILER_FLAG
-- Performing Test COMPILER_RT_HAS_XRAY_COMPILER_FLAG - Failed
-- Performing Test COMPILER_RT_HAS_ATOMIC_KEYWORD
-- Performing Test COMPILER_RT_HAS_ATOMIC_KEYWORD - Success
-- Performing Test COMPILER_RT_HAS_FLOAT16
-- Performing Test COMPILER_RT_HAS_FLOAT16 - Success
-- Performing Test COMPILER_RT_HAS_BFLOAT16
-- Performing Test COMPILER_RT_HAS_BFLOAT16 - Failed
-- Performing Test COMPILER_RT_HAS_ASM_LSE
-- Performing Test COMPILER_RT_HAS_ASM_LSE - Failed
-- Builtin supported architectures: riscv64
-- For riscv64 builtins preferring riscv/muldi3.S to muldi3.c
-- For riscv64 builtins preferring riscv/fp_mode.c to fp_mode.c
-- Supported architectures for crt: riscv64
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pescampus/Desktop/ARA/ara/toolchain/riscv-llvm/compiler-rt/build
cd /home/pescampus/Desktop/ARA/ara/toolchain/riscv-llvm/compiler-rt && \
cmake --build build --target install && \
ln -s /home/pescampus/Desktop/ARA/ara/install/riscv-llvm/lib/linux /home/pescampus/Desktop/ARA/ara/install/riscv-llvm/lib/clang/16/lib
[152/153] Install the project...
-- Install configuration: "l
-- Installing: /home/pescampus/Desktop/ARA/ara/install/riscv-llvm/include/orc/c_api.h
-- Installing: /home/pescampus/Desktop/ARA/ara/install/riscv-llvm/lib/linux/libclang_rt.builtins-riscv64.a
-- Installing: /home/pescampus/Desktop/ARA/ara/install/riscv-llvm/lib/linux/clang_rt.crtbegin-riscv64.o
-- Installing: /home/pescampus/Desktop/ARA/ara/install/riscv-llvm/lib/linux/clang_rt.crtend-riscv64.o
`

Although after this step, hello_world program given in apps has worked fine.
In the next step, i am facing an error in RISC-V tests and no further steps given in README are functioning.
![riscv-tests](https://github.com/pulp-platform/ara/assets/163707576/debd78f7-87d5-417a-b61f-e64285c5bbae)

Please help me resolve this issue, so that I can move further to follow the remaining steps in README successfully.

**Comment by Tanishqgithub** [comment]
I am also facing similar problem can you please resolve the issue

**Comment by mp-17** [comment]
You miss some dependencies. You can try something similar to:

```
sudo apt-get install libncurses5-dev libncursesw5-dev zlib1g-dev libxml2-dev
```
I think you will also need these for the next steps:
```
sudo apt-get install libmpc-dev ninja-build flex libfl-dev help2man libelf-dev
```

(I have not tried these commands on my machine, maybe they need some refinement)

**Comment by Vinay0203** [comment]
I will try with these commands.
Thank you.
