### ISSUE TITLE
invalid arch name error

### ISSUE THREAD

**Issue by sheikhfaizanqureshi** [pulp-platform/ara#307]
After working with v2.2.0 for a while I updated my project repository to v3.0.0. On compiling benchmarks in apps I receive this error: lang-13: error: invalid arch name 'rv64gcv_zfh_zvfh0p1', experimental extension requires explicit version number 'v. (also see attachment)
<img width="952" alt="make_error" src="https://github.com/pulp-platform/ara/assets/150013083/18018b07-6992-4fae-b874-6bbd07f816bf">

Tried many different architecture names/versions but no success.

**Comment by mp-17** [comment]
Hello @sheikhfaizanqureshi, have you also re-installed the toolchains? You need an updated LLVM to be compatible with the new options (try to re-install the toolchain following the readme).
