### ISSUE TITLE
Executing hello_world Program on Vector Unit and generating it's trace file

### ISSUE THREAD

**Issue by Vinay0203** [pulp-platform/ara#309]
I have executed the following commands:
SPIKE Simulation
cd apps
make bin/hello_world.spike
make spike-run-hello_world

After executing the above commands, the hello_world program runs successfully, and I receive the expected output.
My doubt, is this hello_world program being executed on the vector unit?
If the program is indeed running on the vector unit, I would like to generate trace files specifically for the vector unit. I am aware that trace files are generated later in the process, but I am interested in viewing the trace files for the vector unit alone.
Could you please guide me on how to achieve this?

Any guidance or clarification on this would be greatly appreciated.

Thank you!

**Comment by mp-17** [comment]
Hello @Vinay0203,

If you simulate with `spike` (https://github.com/riscv-software-src/riscv-isa-sim), you are NOT running the code on Ara. You are just simulating a dummy vector processor with IPC == 1.

If you want the instruction trace, you can run `spike` in debug mode (https://github.com/riscv-software-src/riscv-isa-sim/blob/master/README.md#interactive-debug-mode). 
When in debug mode, issue a `:r` in the terminal, and you will see the dynamic instruction trace.

**Comment by Vinay0203** [comment]
I will try with this.
Thank you!
