### ISSUE TITLE
similar to #224 

### ISSUE THREAD

**Issue by Tanishqgithub** [pulp-platform/ara#310]
reopening #224 
i need a final conclusion from this issue regarding what are the changes required in  `apps/fmatmul/main.c` so that i get some valid numbers for computation in the output : 
`
=============
=  FMATMUL  =
=============

------------------------------------------------------------
Calculating a (4 x 4) x (4 x 4) matrix multiplication...
------------------------------------------------------------

Calculating fmatmul...
The execution took 0 cycles.
The performance is %f FLOP/cycle (%f% utilization).

------------------------------------------------------------
Calculating a (8 x 8) x (8 x 8) matrix multiplication...
------------------------------------------------------------

Calculating fmatmul...
The execution took 0 cycles.
The performance is %f FLOP/cycle (%f% utilization).

------------------------------------------------------------
Calculating a (16 x 16) x (16 x 16) matrix multiplication...
------------------------------------------------------------

Calculating fmatmul...
The execution took 0 cycles.
The performance is %f FLOP/cycle (%f% utilization).

------------------------------------------------------------
Calculating a (32 x 32) x (32 x 32) matrix multiplication...
------------------------------------------------------------

Calculating fmatmul...
The execution took 0 cycles.
The performance is %f FLOP/cycle (%f% utilization).

------------------------------------------------------------
Calculating a (64 x 64) x (64 x 64) matrix multiplication...
------------------------------------------------------------

Calculating fmatmul...
The execution took 0 cycles.
The performance is %f FLOP/cycle (%f% utilization).

------------------------------------------------------------
Calculating a (128 x 128) x (128 x 128) matrix multiplication...
------------------------------------------------------------

Calculating fmatmul...
The execution took 0 cycles.
The performance is %f FLOP/cycle (%f% utilization).
Verifying result...
Passed.`

**Comment by mp-17** [comment]
Hello @Tanishqgithub,

You are running `fmatmul` on `spike` and not on Ara, right? 
As said in https://github.com/pulp-platform/ara/issues/224, printing in integer or hex should do the trick if you need to print numbers. Have you already tried?
Also, you cannot get useful numbers with `spike` since it's just simulating a processor with IPC == 1.
