### ISSUE TITLE
Error when compiling hello_world

### ISSUE THREAD

**Issue by strongwind312** [pulp-platform/ara#32]
i'm trying to run make bin/hello_world, but i got the following errors:

make bin/hello_world
/home/workspace/pulp/ara_lenovo_unix/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -mcmodel=medany -march=rv64gcv -mabi=lp64 -I/home/workspace/pulp/ara_lenovo_unix/apps/common -static -std=gnu99 -O3 -ffast-math -fno-common -fno-builtin-printf -DNR_LANES=4 -Wunused-variable -Wall -Wextra  -c hello_world/main.c -o hello_world/main.c.o
/home/workspace/pulp/ara_lenovo_unix/install/riscv-gcc/bin/riscv64-unknown-elf-gcc -mcmodel=medany -march=rv64gcv -mabi=lp64 -I/home/workspace/pulp/ara_lenovo_unix/apps/common -static -std=gnu99 -O3 -ffast-math -fno-common -fno-builtin-printf -DNR_LANES=4 -Wunused-variable -Wall -Wextra  -c common/crt0.S -o common/crt0.S.o
common/encoding.h: Assembler messages:
common/encoding.h:1: Error: unknown pseudo-op: `..'
common/crt0.S:80: Error: illegal operands `li t0,PMP_NAPOT|PMP_R|PMP_W|PMP_X'
common/crt0.S:92: Error: illegal operands `li t0,(1<<CAUSE_LOAD_PAGE_FAULT)|(1<<CAUSE_STORE_PAGE_FAULT)|(1<<CAUSE_FETCH_PAGE_FAULT)|(1<<CAUSE_MISALIGNED_FETCH)|(1<<CAUSE_USER_ECALL)|(1<<CAUSE_BREAKPOINT)'
common/crt0.S:102: Error: illegal operands `li t0,(MSTATUS_FS&(MSTATUS_FS>>1))'
common/crt0.S:106: Error: illegal operands `li t0,(MSTATUS_VS&(MSTATUS_VS>>1))'
/home/workspace/pulp/ara_lenovo_unix/apps/common/runtime.mk:66: recipe for target 'common/crt0.S.o' failed
make: *** [common/crt0.S.o] Error 1
rm hello_world/main.c.o

what could be the reason for this ?

**Comment by suehtamacv** [comment]
Hi @strongwind312,

I wonder if you are not missing the `encoding.h` file, which contains the definitions of macros such as `PMP_NAPOT` or `MSTATUS_FS`, and so on. In Ara, this file is available in `apps/common/encoding.h` as a soft-link to the file inside the Spike submodule. 

Do you have this `encoding.h` file? Can you read it?

**Comment by strongwind312** [comment]
Thank you for your help @suehtamacv 
I have encoding.h,
![Image 5](https://user-images.githubusercontent.com/51360494/113650345-a3270f80-96c2-11eb-81c1-41fe86349e8c.png)
and the real file is located in toolchain/riscv-isa-sim/riscv/encoding.h, it contains the required macro definitions.
![Image 6](https://user-images.githubusercontent.com/51360494/113650549-f5683080-96c2-11eb-8b5d-dfc7b5ec7bbe.png)

I think the problem may be the relative file path "../../xxx", if i copy toolchain/riscv-isa-sim/riscv/encoding.h to apps/common to replace the original encoding.h, make bin/hello_world can run correctly.

**Comment by suehtamacv** [comment]
That is interesting... I cannot reproduce it, but I have no issues in making a copy of `encoding.h` to the `apps/common` folder. I will open a PR to handle that.

**Comment by suehtamacv** [comment]
Hi @strongwind312,

I created a new branch, `encoding`, which replaces the softlink by a copy of `encoding.h`. Could you please check whether it solves your issue?

**Comment by strongwind312** [comment]
Ok, i will have a try and feed back later. @suehtamacv

**Comment by strongwind312** [comment]
Hi, @suehtamacv ,
the encoding branch solved my problem.
