### ISSUE TITLE
uint64_t

### ISSUE THREAD

**Issue by grigohas** [pulp-platform/ara#331]
Hello, i do make riscv-isa-sim but i get an error for the uint64_t of the device.h file and i checked that there isn't the cstdint library defined but when i add it and do make again , the device.h file is regenerated without the cstdint header. How can i solve this error?

**Comment by egor-achkasov** [comment]
Could you try downgrading gcc to the version 12 and running the build again? My guess us that the issue is due to a reduced usage of several headers (including cstdint that defines uint64_t) in the gcc implementation.

**Comment by grigohas** [comment]
it worked thanks
