### ISSUE TITLE
half-precision floating point example code

### ISSUE THREAD

**Issue by shkim-emily** [pulp-platform/ara#332]
RVV 1.0 supports floating-point operations only for single precision and double precision. However, Ara2 hardware also supports half-precision floating-point and bfloat operations. Could you provide example code for testing a 16-bit floating-point matmul on Ara2?

**Comment by mp-17** [comment]
Hey @shkim-emily, 

[Here](https://github.com/pulp-platform/ara/blob/main/apps/dtype-matmul/kernel/hp-fmatmul.c) we have 16-bit (half) float.
