### ISSUE TITLE
Assembly level Vector Instructions programs for ARA

### ISSUE THREAD

**Issue by Tanishqgithub** [pulp-platform/ara#336]
Can we run Assembly level Vector programs on ARA 
If so in which file i have to give i/p so that this assembly level program is running on ARA

In this Assembly level program i will make use of vector instructions in RVV 1.0 and write a program and try to execute in ARA 
Is this feature available for ARA?

**Comment by mp-17** [comment]
Hey @Tanishqgithub,

Yes, look at the [examples](https://github.com/pulp-platform/ara/blob/main/apps/fconv3d/fconv3d_3x7x7.c#L181) in the `apps` folder. You can use [gcc extended assembly](https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html) freely.
