### ISSUE TITLE
Additional readme steps

### ISSUE THREAD

**Issue by GeertenV** [pulp-platform/ara#346]
My compliments to how self contained and self explanatory this project and the readme.md are.
However to complete installation and get a successful run of "make verilate" and "make riscv_tests_simv" I needed the following 3 extra steps:
sudo apt install libelf-dev
sudo apt install help2man
make toolchain-gcc
Could this be added to the instructions or would this be only applicable for my case?

**Comment by mp-17** [comment]
Hello @GeertenV,

Thanks a lot! Yes, we can start listing the dependencies in the README since they are not yet available.
