### ISSUE TITLE
Error when nr_lanes changed to 8 and run make verilate

### ISSUE THREAD

**Issue by strongwind312** [pulp-platform/ara#38]
I changed nr_lanes in config/config.mk to 8, but when i ran make verilate, i got the following error :
![Image 1](https://user-images.githubusercontent.com/51360494/114334318-e7ac2280-9b7c-11eb-9b5a-d60a9364373d.png)
so did the combination of nr_lanes=8 and vlen=4096 tested ? and are there any usable combinations except na_lanes=4 and vlen=4096 ?

**Comment by suehtamacv** [comment]
Hi @strongwind312,

Sorry for the delay in tackling this issue. Indeed, Ara has only currently been tested with four lanes. I started adding support for the other configurations. You can track my work on #50.

Matheus
