### ISSUE TITLE
Add support for vector floating-point division and square-root instructions

### ISSUE THREAD

**Issue by mp-17** [pulp-platform/ara#4]
Currently, Ara supports the most important FP operations to run a `matmul` kernel. 
All the other vector floating-point instructions still need to be added. 

Note:
Some of them, namely:
 - `vfclass`
 - `vfdiv`
 - `vfsqrt`

are not implemented due to issues with the FPU (`fpnew`) when operating in vectorial (SIMD) mode. Once these problems are solved, the corresponding instructions will be added as well.

**Comment by suehtamacv** [comment]
Is there a corresponding issue in the `fpnew` repo? As far as I know, this is not an issue with Ara, but rather on how the `fpnew` handles the vector execution of those instructions.

**Comment by mp-17** [comment]
This is a reference to the synch issue that affects `vfdiv` in `fpnew`: https://github.com/pulp-platform/fpnew/issues/45
We will add the new issue for `vfclass` soon; I have opened an issue here as well just as a reminder, as the implementation of these instructions in Ara is stalled by the issues in `fpnew`

**Comment by Xavier2979** [comment]
> Currently, Ara supports the most important FP operations to run a `matmul` kernel.
> All the other vector floating-point instructions still need to be added.
> 
> Note:
> Some of them, namely:
> 
> * `vfclass`
> * `vfdiv`
> * `vfsqrt`
> 
> are not implemented due to issues with the FPU (`fpnew`) when operating in vectorial (SIMD) mode. Once these problems are solved, the corresponding instructions will be added as well.

**Comment by mp-17** [comment]
Due to a delay in updating the FPU, these instructions were delayed as well. We are merging them now with PR https://github.com/pulp-platform/ara/pull/100.
