### ISSUE TITLE
Virtual memory support 

### ISSUE THREAD

**Issue by zaazad** [pulp-platform/ara#45]
Currently Ara works in the bare metal mode. So to support virtual memory and Linux in Ara, we need:

- TLB logic in Ara (addrgen module?)
- TLB miss handling-page walk
- TLB shootdown mechanism
- Page fault (and interrupt?) handling (Based on the RISC-V vector spec, precise exceptions are required for virtual memory support)
- Context switching

**Comment by mp-17** [comment]
Hello zaazad,

Thanks for opening this issue: VM support is an important milestone. Currently, we are focusing our efforts on alignment with the specs + verification + benchmarking, would you like to contribute to the project helping us on implementing VM supports on Ara?

**Comment by dpetrisko** [comment]
Hi, curious if this ever became supported. Thanks!

**Comment by mp-17** [comment]
Hello @dpetrisko,
What a timing! We are actively working on it right now (virtual memory + OS support). It's not ready yet, but if you are also working on it, we can definitely sync.

**Comment by mp-17** [comment]
Addressing this with https://github.com/pulp-platform/ara/pull/311 :-)
