### ISSUE TITLE
On the implementation of FPGA

### ISSUE THREAD

**Issue by Fog-cake** [pulp-platform/ara#49]
Excuse me, do you have plans to release a fpga example project? This can actually run more programs better than simulation. cva
6 has related FPGA projects, but you seem to use many other peripheral ips.

**Comment by Fog-cake** [comment]
I am currently trying to implement your design on FPGA. It is found that some function functions, such as idx_width, under different Nrlane parameters, will not match the data bit width declared by you. For example, what you declare is a logic signal, but the idx_width may be limited by the bit width. Even if it is 1bit, the vivado software will report an error.

**Comment by mp-17** [comment]
Hello Fog-cake,

Thanks a lot for the inputs! We will have a deeper look at it. An FPGA project for Ara is planned, but not in the immediate future. Nevertheless, if you are interested, we would really appreciate your contribution and thoughts on this!

**Comment by fantasysee** [comment]
Thank you for your patient and warm reply, @suehtamacv and @niwis . 

Best Regards,
Chao

**Comment by Fog-cake** [comment]
Hi, @niwis

Can I reduce the required FPGA resources by configuring parameters such as vlen? Thank you.

**Comment by Jett-tu** [comment]
hello
Which files is the top module if I want to implementation of Ara on an FPGA?

**Comment by hossein1387** [comment]
@Jett-tu You can  follow up on this PR https://github.com/pulp-platform/ara/pull/146
