### ISSUE TITLE
”make riscv-isa-sim“ may fail on some network！

### ISSUE THREAD

**Issue by dongdeji** [pulp-platform/ara#64]
In may network, we can not access this kind of url like: "git clone git://git. ....", since this is old format of github url, we suggest it to http format.

ara/Makefile line 131 "git clone git://git.kernel.org/pub/scm/utils/dtc/dtc.git" changing to "git clone https://git.kernel.org/pub/scm/utils/dtc/dtc.git" will be better, since this is the github's offical format.

Best Wishes

**Comment by mp-17** [comment]
Thanks a lot, addressed here https://github.com/pulp-platform/ara/pull/71

Best,
Matteo
