### ISSUE TITLE
Can this support just verilator to simulate, since not everyone can get vsim license?

### ISSUE THREAD

**Issue by dongdeji** [pulp-platform/ara#65]
Best Wishes!

**Comment by suehtamacv** [comment]
Hi @dongdeji 

Actually, Ara does support Verilator for simulation. We use it, for example, in the CI of this repo. You can simulate everything with either QuestaSim or Verilator, although you might need a few fixes (see #62) to get tracing to work with Verilator. In the `hardware` folder, use `make simv` to run simulations on Ara with Verilator.

Matheus
