### ISSUE TITLE
”make verilator“fail with ”CC=$(CLANG_CC) CXX=$(CLANG_CXX) CXXFLAGS=$(CLANG_CXXFLAGS) LDFLAGS=$(CLANG_LDFLAGS) \“ configed.

### ISSUE THREAD

**Issue by dongdeji** [pulp-platform/ara#66]
fail information:
In file included from ../V3Combine.cpp:27:
../V3DupFinder.h:50:5: error: constructor for 'V3DupFinder' must explicitly initialize the const member 'm_hasher'
    V3DupFinder(){};
    ^
../V3DupFinder.h:46:20: note: 'm_hasher' declared here
    const V3Hasher m_hasher;
                   ^
1 error generated.
../Makefile_obj:297: recipe for target 'V3Combine.o' failed
make[3]: *** [V3Combine.o] Error 1

But if i del "CC=$(CLANG_CC) CXX=$(CLANG_CXX) CXXFLAGS=$(CLANG_CXXFLAGS) LDFLAGS=$(CLANG_LDFLAGS) \" this, all version of verilator can compile succeed!

Best Wishes!

**Comment by suehtamacv** [comment]
Hi @dongdeji 

Do you have `CLANG_CC` and `CLANG_CXX` defined to be something? This is something we use internally, but if you do not have those defined in your machine, I do not think this should change anything...

Matheus

**Comment by dongdeji** [comment]
Yes, we have no CLANG_?? anything to be set, and del this seting to continue my compiling.

Best Wishes!

**Comment by suehtamacv** [comment]
Which version of the `clang` compiler are you using to compile Verilator?

**Comment by zhuxuanlong** [comment]
> Which version of the `clang` compiler are you using to compile Verilator?

Hi
The same phenomenon occurs when I compile verilator.   The Clang is compiled from riscv llvm.

`configure:2638: checking for C compiler version
configure:2647: clang --version >&5
clang version 13.0.0 (https://github.com/llvm/llvm-project.git b14c8f5f6eb96e70adb553cc8a4257524881e029)
Target: riscv64-unknown-unknown-elf
Thread model: posix
InstalledDir: /share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/bin
configure:2658: $? = 0
configure:2647: clang -v >&5
clang version 13.0.0 (https://github.com/llvm/llvm-project.git b14c8f5f6eb96e70adb553cc8a4257524881e029)
Target: riscv64-unknown-unknown-elf
Thread model: posix
InstalledDir: /share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/bin
Found candidate GCC installation: /usr/lib/gcc-cross/riscv64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc-cross/riscv64-linux-gnu/9
configure:2658: $? = 0
configure:2647: clang -V >&5
clang-13: error: argument to '-V' is missing (expected 1 value)
clang-13: error: no input files
configure:2658: $? = 1
configure:2647: clang -qversion >&5
clang-13: error: unknown argument '-qversion'; did you mean '--version'?
clang-13: error: no input files
configure:2658: $? = 1
configure:2678: checking whether the C compiler works
configure:2700: clang       conftest.c  >&5
/share/zhuxuanlong/riscv-toolchain/bin/riscv64-unknown-elf-ld: cannot find crt0.o: No such file or directory
clang-13: error: ld command failed with exit code 1 (use -v to see invocation)
configure:2704: $? = 1
configure:2742: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Verilator"
| #define PACKAGE_TARNAME "verilator"
| #define PACKAGE_VERSION "4.210 2021-07-07"
| #define PACKAGE_STRING "Verilator 4.210 2021-07-07"
| #define PACKAGE_BUGREPORT "https://verilator.org"
| #define PACKAGE_URL "https://verilator.org"
| #define PACKAGE_VERSION_NUMBER_STRING "4.210"
| /* end confdefs.h.  */`

**Comment by kuopinghsu** [comment]
Verilator does not work on clang 12, even on clang 13, see #59. I think this is an issue on Verilator.  I have no problem using clang 11.

**Comment by zhuxuanlong** [comment]
> Verilator does not work on clang 12, even on clang 13, see #59. I think this is an issue on Verilator. I have no problem using clang 11.

Do I need to manually download and install a version of clang 11? The clang 13 is compiled by riscv llvm

**Comment by suehtamacv** [comment]
Hi @zhuxuanlong 

Based on your report, you are using LLVM compiled for RISC-V to compile Verilator. You actually need to use the LLVM compiled to your host machine ISA to compile Verilator and the target model. The LLVM we ship with Ara does not work for this

Matheus

**Comment by suehtamacv** [comment]
@mp-17 I guess we could compile LLVM for the host machine ISA as well, but that might be not needed when the user already has an up-to-date LLVM installed. I could see this as a point against that...
