### ISSUE TITLE
”git submodule update --init toolchain/newlib“ may fail on some network!

### ISSUE THREAD

**Issue by dongdeji** [pulp-platform/ara#67]
Changing .gitmodules line 29 from "url = git://sourceware.org/git/newlib-cygwin.git" to "url = https://sourceware.org/git/newlib-cygwin.git" can fix this bug!

Best Wishes!

**Comment by mp-17** [comment]
Hello dongdeji,

Thanks, addressed in https://github.com/pulp-platform/ara/pull/71

Best,
Matteo
