### ISSUE TITLE
Make  bin/hello_world failed

### ISSUE THREAD

**Issue by zhuxuanlong** [pulp-platform/ara#69]
Hi,
The ligloss library cannot be found when compiling hello_world.  When I add the tool chain install directory to the path, the same problem still exists.
`
root@zte-R5300-G4-riscv:/share/zhuxuanlong/Vector_Work/ara/apps# make bin/hello_world
chmod +x /share/zhuxuanlong/Vector_Work/ara/apps/common/script/align_sections.sh
rm -f /share/zhuxuanlong/Vector_Work/ara/apps/common/link.ld && cp /share/zhuxuanlong/Vector_Work/ara/apps/common/arch.link.ld /share/zhuxuanlong/Vector_Work/ara/apps/common/link.ld
/share/zhuxuanlong/Vector_Work/ara/apps/common/script/align_sections.sh 4 /share/zhuxuanlong/Vector_Work/ara/apps/common/link.ld
/share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/bin/clang -march=rv64gcv0p10 -mabi=lp64d -menable-experimental-extensions -mno-relax -fuse-ld=lld -mcmodel=medany -I/share/zhuxuanlong/Vector_Work/ara/apps/common -std=gnu99 -O3 -ffast-math -fno-common -fno-builtin-printf -DNR_LANES=4 -Wunused-variable -Wall -Wextra -Wno-unused-command-line-argument  -c hello_world/main.c -o hello_world/main.c.o
/share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/bin/clang -march=rv64gcv0p10 -mabi=lp64d -menable-experimental-extensions -mno-relax -fuse-ld=lld -mcmodel=medany -I/share/zhuxuanlong/Vector_Work/ara/apps/common -std=gnu99 -O3 -ffast-math -fno-common -fno-builtin-printf -DNR_LANES=4 -Wunused-variable -Wall -Wextra -Wno-unused-command-line-argument  -c common/crt0.S -o common/crt0-llvm.S.o
/share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/bin/clang -march=rv64gcv0p10 -mabi=lp64d -menable-experimental-extensions -mno-relax -fuse-ld=lld -mcmodel=medany -I/share/zhuxuanlong/Vector_Work/ara/apps/common -std=gnu99 -O3 -ffast-math -fno-common -fno-builtin-printf -DNR_LANES=4 -Wunused-variable -Wall -Wextra -Wno-unused-command-line-argument  -c common/printf.c -o common/printf-llvm.c.o
/share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/bin/clang -march=rv64gcv0p10 -mabi=lp64d -menable-experimental-extensions -mno-relax -fuse-ld=lld -mcmodel=medany -I/share/zhuxuanlong/Vector_Work/ara/apps/common -std=gnu99 -O3 -ffast-math -fno-common -fno-builtin-printf -DNR_LANES=4 -Wunused-variable -Wall -Wextra -Wno-unused-command-line-argument  -c common/string.c -o common/string-llvm.c.o
/share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/bin/clang -march=rv64gcv0p10 -mabi=lp64d -menable-experimental-extensions -mno-relax -fuse-ld=lld -mcmodel=medany -I/share/zhuxuanlong/Vector_Work/ara/apps/common -std=gnu99 -O3 -ffast-math -fno-common -fno-builtin-printf -DNR_LANES=4 -Wunused-variable -Wall -Wextra -Wno-unused-command-line-argument  -c common/serial.c -o common/serial-llvm.c.o
mkdir -p bin/
/share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/bin/clang -Iinclude -march=rv64gcv0p10 -mabi=lp64d -menable-experimental-extensions -mno-relax -fuse-ld=lld -mcmodel=medany -I/share/zhuxuanlong/Vector_Work/ara/apps/common -std=gnu99 -O3 -ffast-math -fno-common -fno-builtin-printf -DNR_LANES=4 -Wunused-variable -Wall -Wextra -Wno-unused-command-line-argument  -o bin/hello_world hello_world/main.c.o common/crt0-llvm.S.o common/printf-llvm.c.o common/string-llvm.c.o common/serial-llvm.c.o -static -nostartfiles -lm -T/share/zhuxuanlong/Vector_Work/ara/apps/common/link.ld
ld.lld: error: unable to find library -lgloss
clang-13: error: ld command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:59: bin/hello_world] Error 1
rm hello_world/main.c.o common/string-llvm.c.o common/crt0-llvm.S.o common/printf-llvm.c.o common/serial-llvm.c.o
`

Thank you.

**Comment by mp-17** [comment]
Hello zhuxuanlong,

`libgloss` should be in `/share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/riscv64-unknown-elf/lib`. Can you please report the output of the command:
`ls /share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/riscv64-unknown-elf/lib`?

If it's not there, something went wrong during the installation of newlib.

Let us know! ;-)
Matteo

**Comment by zhuxuanlong** [comment]
> Hello zhuxuanlong,
> 
> `libgloss` should be in `/share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/riscv64-unknown-elf/lib`. Can you please report the output of the command:
> `ls /share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/riscv64-unknown-elf/lib`?
> 
> If it's not there, something went wrong during the installation of newlib.
> 
> Let us know! ;-)
> Matteo

Hi mp-17,
Thank you for your reply. This file exists.


_root@zte-R5300-G4-riscv:/share/zhuxuanlong/Vector_Work/ara/apps# ls ../install/riscv-llvm/riscv64-unknown-elf/lib/
crt0.o  libc.a  libg.a  libgloss.a  libm.a  libnosys.a  libsemihost.a  libsim.a  nano.specs  nosys.specs  rv64imafdc  semihost.specs  sim.specs_

**Comment by mp-17** [comment]
Okay, let's see where the linker searches for the libraries.

Can you please apply this patch to the Makefile in the `apps` directory?

You just need to download [this file](https://github.com/pulp-platform/ara/files/7210058/issue_69_0.txt) in the repository root directory, and then execute from there:

`git apply issue_69_0.txt`

Then, from the `apps` directory, you can try:

`make bin/hello_world | grep "ld.lld"`

Can you please post the output of this command here? We should see now the verbose output of the linker, with the directories that it visit when looking for the libraries.

**Comment by zhuxuanlong** [comment]
> make bin/hello_world | grep "ld.lld"

Thank you. The output of the command is as follows:

`root@zte-R5300-G4-riscv:/share/zhuxuanlong/Vector_Work/ara/apps# make bin/hello_world
chmod +x /share/zhuxuanlong/Vector_Work/ara/apps/common/script/align_sections.sh
rm -f /share/zhuxuanlong/Vector_Work/ara/apps/common/link.ld && cp /share/zhuxuanlong/Vector_Work/ara/apps/common/arch.link.ld /share/zhuxuanlong/Vector_Work/ara/apps/common/link.ld
/share/zhuxuanlong/Vector_Work/ara/apps/common/script/align_sections.sh 4 /share/zhuxuanlong/Vector_Work/ara/apps/common/link.ld
/share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/bin/clang -march=rv64gcv0p10 -mabi=lp64d -menable-experimental-extensions -mno-relax -fuse-ld=lld -mcmodel=medany -I/share/zhuxuanlong/Vector_Work/ara/apps/common -std=gnu99 -O3 -ffast-math -fno-common -fno-builtin-printf -DNR_LANES=4 -Wunused-variable -Wall -Wextra -Wno-unused-command-line-argument  -c hello_world/main.c -o hello_world/main.c.o
/share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/bin/clang -march=rv64gcv0p10 -mabi=lp64d -menable-experimental-extensions -mno-relax -fuse-ld=lld -mcmodel=medany -I/share/zhuxuanlong/Vector_Work/ara/apps/common -std=gnu99 -O3 -ffast-math -fno-common -fno-builtin-printf -DNR_LANES=4 -Wunused-variable -Wall -Wextra -Wno-unused-command-line-argument  -c common/crt0.S -o common/crt0-llvm.S.o
/share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/bin/clang -march=rv64gcv0p10 -mabi=lp64d -menable-experimental-extensions -mno-relax -fuse-ld=lld -mcmodel=medany -I/share/zhuxuanlong/Vector_Work/ara/apps/common -std=gnu99 -O3 -ffast-math -fno-common -fno-builtin-printf -DNR_LANES=4 -Wunused-variable -Wall -Wextra -Wno-unused-command-line-argument  -c common/printf.c -o common/printf-llvm.c.o
/share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/bin/clang -march=rv64gcv0p10 -mabi=lp64d -menable-experimental-extensions -mno-relax -fuse-ld=lld -mcmodel=medany -I/share/zhuxuanlong/Vector_Work/ara/apps/common -std=gnu99 -O3 -ffast-math -fno-common -fno-builtin-printf -DNR_LANES=4 -Wunused-variable -Wall -Wextra -Wno-unused-command-line-argument  -c common/string.c -o common/string-llvm.c.o
/share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/bin/clang -march=rv64gcv0p10 -mabi=lp64d -menable-experimental-extensions -mno-relax -fuse-ld=lld -mcmodel=medany -I/share/zhuxuanlong/Vector_Work/ara/apps/common -std=gnu99 -O3 -ffast-math -fno-common -fno-builtin-printf -DNR_LANES=4 -Wunused-variable -Wall -Wextra -Wno-unused-command-line-argument  -c common/serial.c -o common/serial-llvm.c.o
mkdir -p bin/
/share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/bin/clang -Iinclude -march=rv64gcv0p10 -mabi=lp64d -menable-experimental-extensions -mno-relax -fuse-ld=lld -mcmodel=medany -I/share/zhuxuanlong/Vector_Work/ara/apps/common -std=gnu99 -O3 -ffast-math -fno-common -fno-builtin-printf -DNR_LANES=4 -Wunused-variable -Wall -Wextra -Wno-unused-command-line-argument  -o bin/hello_world hello_world/main.c.o common/crt0-llvm.S.o common/printf-llvm.c.o common/string-llvm.c.o common/serial-llvm.c.o -static -nostartfiles -lm -T/share/zhuxuanlong/Vector_Work/ara/apps/common/link.ld -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git b14c8f5f6eb96e70adb553cc8a4257524881e029)
Target: riscv64-unknown-unknown-elf
Thread model: posix
InstalledDir: /share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/bin
Found candidate GCC installation: /usr/lib/gcc-cross/riscv64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc-cross/riscv64-linux-gnu/9
 "/share/zhuxuanlong/Vector_Work/ara/install/riscv-llvm/bin/ld.lld" -m elf64lriscv hello_world/main.c.o common/crt0-llvm.S.o common/printf-llvm.c.o common/string-llvm.c.o common/serial-llvm.c.o -lm -L/usr/lib/gcc-cross/riscv64-linux-gnu/9 -L/usr/lib/gcc-cross/riscv64-linux-gnu/9/../../../../riscv64-linux-gnu/lib -T /share/zhuxuanlong/Vector_Work/ara/apps/common/link.ld --start-group -lc -lgloss --end-group -lgcc -o bin/hello_world
ld.lld: error: unable to find library -lgloss
clang-13: error: ld command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:59: bin/hello_world] Error 1
rm hello_world/main.c.o common/string-llvm.c.o common/crt0-llvm.S.o common/printf-llvm.c.o common/serial-llvm.c.o
`

**Comment by mp-17** [comment]
Your LLVM found a candidate RISC-V GCC installation on the system and it is searching for libraries there. 
I must change the options we give to LLVM when it is installed to fix this in a more elegant way, but, in the meantime, you can apply another patch to solve the problem.

Revert the patch that you applied before, from the root repository directory:
`git checkout -- apps/Makefile`

Download and apply the [new patch](https://github.com/pulp-platform/ara/files/7211697/issue_69_1.txt):
`git apply issue_69_1.txt`

Then, it should compile smoothly. Let us know!

Best,
Matteo

**Comment by zhuxuanlong** [comment]
> Your LLVM found a candidate RISC-V GCC installation on the system and it is searching for libraries there.
> I must change the options we give to LLVM when it is installed to fix this in a more elegant way, but, in the meantime, you can apply another patch to solve the problem.
> 
> Revert the patch that you applied before, from the root repository directory:
> `git checkout -- apps/Makefile`
> 
> Download and apply the [new patch](https://github.com/pulp-platform/ara/files/7211697/issue_69_1.txt):
> `git apply issue_69_1.txt`
> 
> Then, it should compile smoothly. Let us know!
> 
> Best,
> Matteo

Hi Matteo,
The above solution can solve the helloword compilation error. Thank you again for your support.  In addition, two targets need to be modified in the apps/makefile, such as `bin/$(1)-ara-%` and `bin/$(1)-ara-%.` Otherwise, `make riscv_tests` has the same problem. 
After compilation, all executable programs under bin are as follows:

`root@zte-R5300-G4-riscv:/share/zhuxuanlong/Vector_Work/ara/ara/apps# ls bin/
hello_world                   rv64ud-ara-structural.dump  rv64ui-ara-bgeu          rv64ui-ara-simple.dump  rv64ui-ara-xori         rv64uv-ara-vfcvt.dump         rv64uv-ara-vfsub          rv64uv-ara-vmfge.dump    rv64uv-ara-vmulh             rv64uv-ara-vslidedown.dump
hello_world.dump              rv64uf-ara-fadd             rv64ui-ara-bgeu.dump     rv64ui-ara-sll          rv64ui-ara-xori.dump    rv64uv-ara-vfmacc             rv64uv-ara-vfsub.dump     rv64uv-ara-vmfgt         rv64uv-ara-vmulh.dump        rv64uv-ara-vslideup
rv64si-ara-csr                rv64uf-ara-fadd.dump        rv64ui-ara-blt           rv64ui-ara-sll.dump     rv64um-ara-div          rv64uv-ara-vfmacc.dump        rv64uv-ara-vfwadd         rv64uv-ara-vmfgt.dump    rv64uv-ara-vmulhsu           rv64uv-ara-vslideup.dump
rv64si-ara-csr.dump           rv64uf-ara-fclass           rv64ui-ara-blt.dump      rv64ui-ara-slli         rv64um-ara-div.dump     rv64uv-ara-vfmadd             rv64uv-ara-vfwadd.dump    rv64uv-ara-vmfle         rv64uv-ara-vmulhsu.dump      rv64uv-ara-vsll
rv64si-ara-dirty              rv64uf-ara-fclass.dump      rv64ui-ara-bltu          rv64ui-ara-slli.dump    rv64um-ara-divu         rv64uv-ara-vfmadd.dump        rv64uv-ara-vfwcvt         rv64uv-ara-vmfle.dump    rv64uv-ara-vmulhu            rv64uv-ara-vsll.dump
rv64si-ara-dirty.dump         rv64uf-ara-fcmp             rv64ui-ara-bltu.dump     rv64ui-ara-slliw        rv64um-ara-divu.dump    rv64uv-ara-vfmax              rv64uv-ara-vfwcvt.dump    rv64uv-ara-vmflt         rv64uv-ara-vmulhu.dump       rv64uv-ara-vsra
rv64si-ara-icache-alias       rv64uf-ara-fcmp.dump        rv64ui-ara-bne           rv64ui-ara-slliw.dump   rv64um-ara-divuw        rv64uv-ara-vfmax.dump         rv64uv-ara-vfwmacc        rv64uv-ara-vmflt.dump    rv64uv-ara-vmv               rv64uv-ara-vsra.dump
rv64si-ara-icache-alias.dump  rv64uf-ara-fcvt             rv64ui-ara-bne.dump      rv64ui-ara-sllw         rv64um-ara-divuw.dump   rv64uv-ara-vfmerge            rv64uv-ara-vfwmacc.dump   rv64uv-ara-vmfne         rv64uv-ara-vmv.dump          rv64uv-ara-vsrl
rv64si-ara-ma_fetch           rv64uf-ara-fcvt.dump        rv64ui-ara-fence_i       rv64ui-ara-sllw.dump    rv64um-ara-divw         rv64uv-ara-vfmerge.dump       rv64uv-ara-vfwmsac        rv64uv-ara-vmfne.dump    rv64uv-ara-vmxnor            rv64uv-ara-vsrl.dump
rv64si-ara-ma_fetch.dump      rv64uf-ara-fcvt_w           rv64ui-ara-fence_i.dump  rv64ui-ara-slt          rv64um-ara-divw.dump    rv64uv-ara-vfmin              rv64uv-ara-vfwmsac.dump   rv64uv-ara-vmin          rv64uv-ara-vmxnor.dump       rv64uv-ara-vss
rv64si-ara-sbreak             rv64uf-ara-fcvt_w.dump      rv64ui-ara-jal           rv64ui-ara-slt.dump     rv64um-ara-mul          rv64uv-ara-vfmin.dump         rv64uv-ara-vfwmul         rv64uv-ara-vmin.dump     rv64uv-ara-vmxor             rv64uv-ara-vss.dump
rv64si-ara-sbreak.dump        rv64uf-ara-fdiv             rv64ui-ara-jal.dump      rv64ui-ara-slti         rv64um-ara-mul.dump     rv64uv-ara-vfmsac             rv64uv-ara-vfwmul.dump    rv64uv-ara-vminu         rv64uv-ara-vmxor.dump        rv64uv-ara-vsub
rv64si-ara-scall              rv64uf-ara-fdiv.dump        rv64ui-ara-jalr          rv64ui-ara-slti.dump    rv64um-ara-mulh         rv64uv-ara-vfmsac.dump        rv64uv-ara-vfwnmacc       rv64uv-ara-vminu.dump    rv64uv-ara-vnmsac            rv64uv-ara-vsub.dump
rv64si-ara-scall.dump         rv64uf-ara-fmadd            rv64ui-ara-jalr.dump     rv64ui-ara-sltiu        rv64um-ara-mulh.dump    rv64uv-ara-vfmsub             rv64uv-ara-vfwnmacc.dump  rv64uv-ara-vmnand        rv64uv-ara-vnmsac.dump       rv64uv-ara-vwadd
rv64si-ara-wfi                rv64uf-ara-fmadd.dump       rv64ui-ara-lb            rv64ui-ara-sltiu.dump   rv64um-ara-mulhsu       rv64uv-ara-vfmsub.dump        rv64uv-ara-vfwnmsac       rv64uv-ara-vmnand.dump   rv64uv-ara-vnmsub            rv64uv-ara-vwadd.dump
rv64si-ara-wfi.dump           rv64uf-ara-fmin             rv64ui-ara-lb.dump       rv64ui-ara-sltu         rv64um-ara-mulhsu.dump  rv64uv-ara-vfmul              rv64uv-ara-vfwnmsac.dump  rv64uv-ara-vmnor         rv64uv-ara-vnmsub.dump       rv64uv-ara-vwaddu
rv64uc-ara-rvc                rv64uf-ara-fmin.dump        rv64ui-ara-lbu           rv64ui-ara-sltu.dump    rv64um-ara-mulhu        rv64uv-ara-vfmul.dump         rv64uv-ara-vfwsub         rv64uv-ara-vmnor.dump    rv64uv-ara-vnsra             rv64uv-ara-vwaddu.dump
rv64uc-ara-rvc.dump           rv64uf-ara-ldst             rv64ui-ara-lbu.dump      rv64ui-ara-sra          rv64um-ara-mulhu.dump   rv64uv-ara-vfmv               rv64uv-ara-vfwsub.dump    rv64uv-ara-vmor          rv64uv-ara-vnsra.dump        rv64uv-ara-vwmacc
rv64ud-ara-fadd               rv64uf-ara-ldst.dump        rv64ui-ara-ld            rv64ui-ara-sra.dump     rv64um-ara-mulw         rv64uv-ara-vfmv.dump          rv64uv-ara-vl             rv64uv-ara-vmor.dump     rv64uv-ara-vnsrl             rv64uv-ara-vwmacc.dump
rv64ud-ara-fadd.dump          rv64uf-ara-move             rv64ui-ara-ld.dump       rv64ui-ara-srai         rv64um-ara-mulw.dump    rv64uv-ara-vfncvt             rv64uv-ara-vl.dump        rv64uv-ara-vmornot       rv64uv-ara-vnsrl.dump        rv64uv-ara-vwmaccsu
rv64ud-ara-fclass             rv64uf-ara-move.dump        rv64ui-ara-lh            rv64ui-ara-srai.dump    rv64um-ara-rem          rv64uv-ara-vfncvt.dump        rv64uv-ara-vls            rv64uv-ara-vmornot.dump  rv64uv-ara-vor               rv64uv-ara-vwmaccsu.dump
rv64ud-ara-fclass.dump        rv64uf-ara-recoding         rv64ui-ara-lh.dump       rv64ui-ara-sraiw        rv64um-ara-rem.dump     rv64uv-ara-vfnmacc            rv64uv-ara-vls.dump       rv64uv-ara-vmsbc         rv64uv-ara-vor.dump          rv64uv-ara-vwmaccu
rv64ud-ara-fcmp               rv64uf-ara-recoding.dump    rv64ui-ara-lhu           rv64ui-ara-sraiw.dump   rv64um-ara-remu         rv64uv-ara-vfnmacc.dump       rv64uv-ara-vmacc          rv64uv-ara-vmsbc.dump    rv64uv-ara-vrem              rv64uv-ara-vwmaccu.dump
rv64ud-ara-fcmp.dump          rv64ui-ara-add              rv64ui-ara-lhu.dump      rv64ui-ara-sraw         rv64um-ara-remu.dump    rv64uv-ara-vfnmadd            rv64uv-ara-vmacc.dump     rv64uv-ara-vmseq         rv64uv-ara-vrem.dump         rv64uv-ara-vwmaccus
rv64ud-ara-fcvt               rv64ui-ara-add.dump         rv64ui-ara-lui           rv64ui-ara-sraw.dump    rv64um-ara-remuw        rv64uv-ara-vfnmadd.dump       rv64uv-ara-vmadc          rv64uv-ara-vmseq.dump    rv64uv-ara-vremu             rv64uv-ara-vwmaccus.dump
rv64ud-ara-fcvt.dump          rv64ui-ara-addi             rv64ui-ara-lui.dump      rv64ui-ara-srl          rv64um-ara-remuw.dump   rv64uv-ara-vfnmsac            rv64uv-ara-vmadc.dump     rv64uv-ara-vmsgt         rv64uv-ara-vremu.dump        rv64uv-ara-vwmul
rv64ud-ara-fcvt_w             rv64ui-ara-addi.dump        rv64ui-ara-lw            rv64ui-ara-srl.dump     rv64um-ara-remw         rv64uv-ara-vfnmsac.dump       rv64uv-ara-vmadd          rv64uv-ara-vmsgt.dump    rv64uv-ara-vrsub             rv64uv-ara-vwmul.dump
rv64ud-ara-fcvt_w.dump        rv64ui-ara-addiw            rv64ui-ara-lw.dump       rv64ui-ara-srli         rv64um-ara-remw.dump    rv64uv-ara-vfnmsub            rv64uv-ara-vmadd.dump     rv64uv-ara-vmsgtu        rv64uv-ara-vrsub.dump        rv64uv-ara-vwmulsu
rv64ud-ara-fdiv               rv64ui-ara-addiw.dump       rv64ui-ara-lwu           rv64ui-ara-srli.dump    rv64uv-ara-vadc         rv64uv-ara-vfnmsub.dump       rv64uv-ara-vmand          rv64uv-ara-vmsgtu.dump   rv64uv-ara-vs                rv64uv-ara-vwmulsu.dump
rv64ud-ara-fdiv.dump          rv64ui-ara-addw             rv64ui-ara-lwu.dump      rv64ui-ara-srliw        rv64uv-ara-vadc.dump    rv64uv-ara-vfrsub             rv64uv-ara-vmand.dump     rv64uv-ara-vmsle         rv64uv-ara-vsbc              rv64uv-ara-vwmulu
rv64ud-ara-fmadd              rv64ui-ara-addw.dump        rv64ui-ara-or            rv64ui-ara-srliw.dump   rv64uv-ara-vadd         rv64uv-ara-vfrsub.dump        rv64uv-ara-vmandnot       rv64uv-ara-vmsle.dump    rv64uv-ara-vsbc.dump         rv64uv-ara-vwmulu.dump
rv64ud-ara-fmadd.dump         rv64ui-ara-and              rv64ui-ara-or.dump       rv64ui-ara-srlw         rv64uv-ara-vadd.dump    rv64uv-ara-vfsgnj             rv64uv-ara-vmandnot.dump  rv64uv-ara-vmsleu        rv64uv-ara-vs.dump           rv64uv-ara-vwsub
rv64ud-ara-fmin               rv64ui-ara-and.dump         rv64ui-ara-ori           rv64ui-ara-srlw.dump    rv64uv-ara-vand         rv64uv-ara-vfsgnj.dump        rv64uv-ara-vmax           rv64uv-ara-vmsleu.dump   rv64uv-ara-vsetivli          rv64uv-ara-vwsub.dump
rv64ud-ara-fmin.dump          rv64ui-ara-andi             rv64ui-ara-ori.dump      rv64ui-ara-sub          rv64uv-ara-vand.dump    rv64uv-ara-vfsgnjn            rv64uv-ara-vmax.dump      rv64uv-ara-vmslt         rv64uv-ara-vsetivli.dump     rv64uv-ara-vwsubu
rv64ud-ara-ldst               rv64ui-ara-andi.dump        rv64ui-ara-sb            rv64ui-ara-sub.dump     rv64uv-ara-vdiv         rv64uv-ara-vfsgnjn.dump       rv64uv-ara-vmaxu          rv64uv-ara-vmslt.dump    rv64uv-ara-vsext             rv64uv-ara-vwsubu.dump
rv64ud-ara-ldst.dump          rv64ui-ara-auipc            rv64ui-ara-sb.dump       rv64ui-ara-subw         rv64uv-ara-vdiv.dump    rv64uv-ara-vfsgnjx            rv64uv-ara-vmaxu.dump     rv64uv-ara-vmsltu        rv64uv-ara-vsext.dump        rv64uv-ara-vxor
rv64ud-ara-move               rv64ui-ara-auipc.dump       rv64ui-ara-sd            rv64ui-ara-subw.dump    rv64uv-ara-vdivu        rv64uv-ara-vfsgnjx.dump       rv64uv-ara-vmerge         rv64uv-ara-vmsltu.dump   rv64uv-ara-vslide1down       rv64uv-ara-vxor.dump
rv64ud-ara-move.dump          rv64ui-ara-beq              rv64ui-ara-sd.dump       rv64ui-ara-sw           rv64uv-ara-vdivu.dump   rv64uv-ara-vfslide1down       rv64uv-ara-vmerge.dump    rv64uv-ara-vmsne         rv64uv-ara-vslide1down.dump  rv64uv-ara-vzext
rv64ud-ara-recoding           rv64ui-ara-beq.dump         rv64ui-ara-sh            rv64ui-ara-sw.dump      rv64uv-ara-vfadd        rv64uv-ara-vfslide1down.dump  rv64uv-ara-vmfeq          rv64uv-ara-vmsne.dump    rv64uv-ara-vslide1up         rv64uv-ara-vzext.dump
rv64ud-ara-recoding.dump      rv64ui-ara-bge              rv64ui-ara-sh.dump       rv64ui-ara-xor          rv64uv-ara-vfadd.dump   rv64uv-ara-vfslide1up         rv64uv-ara-vmfeq.dump     rv64uv-ara-vmul          rv64uv-ara-vslide1up.dump
rv64ud-ara-structural         rv64ui-ara-bge.dump         rv64ui-ara-simple        rv64ui-ara-xor.dump     rv64uv-ara-vfcvt        rv64uv-ara-vfslide1up.dump    rv64uv-ara-vmfge          rv64uv-ara-vmul.dump     rv64uv-ara-vslidedown
`

**Comment by mp-17** [comment]
Perfect, happy that it helped! :-)

Best,
Matteo
