### ISSUE TITLE
How do I segment the output waveform

### ISSUE THREAD

**Issue by little-blue** [pulp-platform/ara#98]
I use the verilator on ara to simulate a benchmark. But the output sim.fst file is too large to analysis. It is almost 39GB. How can I change the ara source code to output multiple files and each of them less than for example 500MB.

**Comment by mp-17** [comment]
Hi little-blue,

I don't know if you can split the trace into smaller files automatically with Verilator, but you can use the `--trace-depth` option to tune the depth of tracing, e.g. `--trace-depth 1` to dump only the top level signals. This should reduce the file size, even if it will also worsen the internal signal visibility.
Do you think this can be useful to you?

Best,
Matteo

**Comment by little-blue** [comment]
Yes, thank you for answer my question, it helps me a lot.
