### ISSUE TITLE
Tracing modules with more depth

### ISSUE THREAD

**Issue by mhezarei** [pulp-platform/ara#99]
Greetings,

After looking at the Verilator's tracing output with GTKWave, I realized that signals from deeper modules (such as `simd_alu`) are not present. Is it intended, or am I making a mistake? If it is normal, then how could I look for deeper modules' waveforms?

I should also mention that the output I saw was generated with the maximum value for `--trace-depth` (passing no value makes the tracing go as deep as possible according to the Verilator guide).

Thanks in advance.

**Comment by alan2031** [comment]
> Hi @mhezarei I had the same problem. Have you found a solution? Thanks in advance.

Comment out line 7 to line 12 in hardware/tb/verilator/waiver.vlt, which blocks lanes.

**Comment by mp-17** [comment]
Fixing with https://github.com/pulp-platform/ara/pull/317/commits/5cec856d417a74bd591808e8b9b1997c0e715d57 in https://github.com/pulp-platform/ara/pull/317
